import { WalmartStoreProfile, ZoneDefinition, WalmartZoneId } from '@/lib/types';

export const WALMART_ZONES: Record<WalmartZoneId, ZoneDefinition> = {
  ZONE_1_HOUSEHOLD: {
    id: 'ZONE_1_HOUSEHOLD',
    name: 'Household, Baby & Personal Care',
    shortName: 'Household & Baby',
    iconName: 'Sparkles',
    color: 'from-amber-500 to-orange-600',
    badgeBg: 'bg-amber-100 text-amber-900 dark:bg-amber-950 dark:text-amber-200 border-amber-300 dark:border-amber-800',
    description: 'Paper goods, detergent, cleaning supplies, baby items & toys',
    sortWeight: 1,
  },
  ZONE_2_PANTRY_DRY: {
    id: 'ZONE_2_PANTRY_DRY',
    name: 'Heavy Dry Pantry & Specialty (Aisles A1–A25)',
    shortName: 'Pantry Aisles',
    iconName: 'Package',
    color: 'from-blue-600 to-indigo-700',
    badgeBg: 'bg-blue-100 text-blue-900 dark:bg-blue-950 dark:text-blue-200 border-blue-300 dark:border-blue-800',
    description: 'Canned goods, pasta, gluten-free, spices, cereal, snacks & beverages',
    sortWeight: 2,
  },
  ZONE_3_MEAT: {
    id: 'ZONE_3_MEAT',
    name: 'Fresh Meat & Seafood',
    shortName: 'Meat & Seafood',
    iconName: 'Drumstick',
    color: 'from-red-600 to-rose-700',
    badgeBg: 'bg-red-100 text-red-900 dark:bg-red-950 dark:text-red-200 border-red-300 dark:border-red-800',
    description: 'Poultry, beef, pork, bacon, fresh fish',
    sortWeight: 3,
  },
  ZONE_4_DAIRY: {
    id: 'ZONE_4_DAIRY',
    name: 'Dairy & Refrigerated',
    shortName: 'Dairy Wall',
    iconName: 'Milk',
    color: 'from-cyan-600 to-teal-700',
    badgeBg: 'bg-cyan-100 text-cyan-900 dark:bg-cyan-950 dark:text-cyan-200 border-cyan-300 dark:border-cyan-800',
    description: 'Milk, butter, eggs, cheese, yogurt, creamers',
    sortWeight: 4,
  },
  ZONE_5_PRODUCE_BAKERY: {
    id: 'ZONE_5_PRODUCE_BAKERY',
    name: 'Produce & Bakery (Door Zone)',
    shortName: 'Produce & Bakery',
    iconName: 'Apple',
    color: 'from-emerald-600 to-green-700',
    badgeBg: 'bg-emerald-100 text-emerald-900 dark:bg-emerald-950 dark:text-emerald-200 border-emerald-300 dark:border-emerald-800',
    description: 'Delicate fruits, greens, fresh bread, gluten-free bakery, pastries',
    sortWeight: 5,
  },
  ZONE_6_FROZEN: {
    id: 'ZONE_6_FROZEN',
    name: 'Frozen Foods & Ice Cream (Last Stop)',
    shortName: 'Frozen Foods',
    iconName: 'Snowflake',
    color: 'from-indigo-600 to-purple-700',
    badgeBg: 'bg-indigo-100 text-indigo-900 dark:bg-indigo-950 dark:text-indigo-200 border-indigo-300 dark:border-indigo-800',
    description: 'Ice cream, frozen pizza, frozen veggies, meals',
    sortWeight: 6,
  },
  ZONE_7_FRONT: {
    id: 'ZONE_7_FRONT',
    name: 'Front End & Registers',
    shortName: 'Checkout',
    iconName: 'ShoppingCart',
    color: 'from-slate-600 to-gray-800',
    badgeBg: 'bg-slate-100 text-slate-900 dark:bg-slate-800 dark:text-slate-200 border-slate-300 dark:border-slate-700',
    description: 'Registers, self-checkout, grab & go snacks',
    sortWeight: 7,
  },
};

export const DEFAULT_WALMART_STORES: WalmartStoreProfile[] = [
  {
    id: 'walmart-anna-tx',
    storeNumber: '6300',
    name: 'Walmart Supercenter — Anna, TX',
    city: 'Anna',
    state: 'TX',
    zipCode: '75409',
    type: 'Supercenter',
    entranceType: 'GM & Grocery',
  },
  {
    id: 'walmart-melissa-tx',
    storeNumber: '3801',
    name: 'Walmart Supercenter — Melissa, TX',
    city: 'Melissa',
    state: 'TX',
    zipCode: '75454',
    type: 'Supercenter',
    entranceType: 'Grocery Main',
  },
  {
    id: 'walmart-100',
    storeNumber: '100',
    name: 'Walmart Supercenter #100',
    city: 'Bentonville',
    state: 'AR',
    zipCode: '72712',
    type: 'Supercenter',
    entranceType: 'GM & Grocery',
  },
];
